'''
Various util functions to manage model state.
'''
from transformers import AutoConfig, AutoTokenizer, AutoModelForCausalLM
import torch
from torch import nn
from model.constants import MODEL_ID
import os
import psutil
import torch

def resolve_torch_dtype(dtype):
    if isinstance(dtype, torch.dtype):
        return dtype

    if isinstance(dtype, str):
        dtype_name = dtype.removeprefix("torch.")
        resolved_dtype = getattr(torch, dtype_name, None)
        if isinstance(resolved_dtype, torch.dtype):
            return resolved_dtype

    raise TypeError(f"Unsupported torch dtype: {dtype!r}")


# generated by chat
def load_hf_weights(jllama, hf_model):
    """
    Load weights from a Hugging Face LlamaForCausalLM-style model
    into this custom JLlama implementation.

    Args:
        jllama:
            Your JLlama instance.

        hf_model:
            A Hugging Face LlamaForCausalLM / AutoModelForCausalLM instance.

    Returns:
        jllama with HF weights loaded.
    """
    hf_state = hf_model.state_dict()
    new_state = {}

    # Embedding
    new_state["embedding.weight"] = hf_state[
        "model.embed_tokens.weight"
    ]

    # Transformer blocks
    num_layers = len(jllama.layers)

    for i in range(num_layers):
        hf_prefix = f"model.layers.{i}"
        my_prefix = f"layers.{i}"

        # Attention
        new_state[f"{my_prefix}.attention.q_proj.weight"] = hf_state[
            f"{hf_prefix}.self_attn.q_proj.weight"
        ]

        new_state[f"{my_prefix}.attention.k_proj.weight"] = hf_state[
            f"{hf_prefix}.self_attn.k_proj.weight"
        ]

        new_state[f"{my_prefix}.attention.v_proj.weight"] = hf_state[
            f"{hf_prefix}.self_attn.v_proj.weight"
        ]

        new_state[f"{my_prefix}.attention.o_proj.weight"] = hf_state[
            f"{hf_prefix}.self_attn.o_proj.weight"
        ]

        # Attention input RMSNorm
        new_state[f"{my_prefix}.attn_norm.weight"] = hf_state[
            f"{hf_prefix}.input_layernorm.weight"
        ]

        # MLP
        new_state[f"{my_prefix}.mlp.gate_proj.weight"] = hf_state[
            f"{hf_prefix}.mlp.gate_proj.weight"
        ]

        new_state[f"{my_prefix}.mlp.up_proj.weight"] = hf_state[
            f"{hf_prefix}.mlp.up_proj.weight"
        ]

        new_state[f"{my_prefix}.mlp.down_proj.weight"] = hf_state[
            f"{hf_prefix}.mlp.down_proj.weight"
        ]

        # Post-attention RMSNorm
        new_state[f"{my_prefix}.mlp_norm.weight"] = hf_state[
            f"{hf_prefix}.post_attention_layernorm.weight"
        ]

    # Final RMSNorm
    new_state["norm.weight"] = hf_state[
        "model.norm.weight"
    ]

    # LM head
    new_state["lm_head.weight"] = hf_state[
        "lm_head.weight"
    ]

    # Validate and load everything
    jllama.load_state_dict(new_state, strict=True)

    return jllama

def load_model() -> dict:
    config = AutoConfig.from_pretrained(MODEL_ID)
    tokenzier = AutoTokenizer.from_pretrained(MODEL_ID)

    hf_model = AutoModelForCausalLM.from_pretrained(
            MODEL_ID,
            # dtype=torch.bfloat16,
            dtype=resolve_torch_dtype(config.dtype),
    )

    personal_model = JLlama(config)

    personal_model = load_hf_weights(personal_model, hf_model)

    return {"tokenizer": tokenzier, "model": personal_model, "config": config}


def benchmark_memory(label: str, device: str):
    process = psutil.Process(os.getpid())
    rss = process.memory_info().rss

    device_allocated = 0
    device_reserved = 0
    device_peak = -1

    if device == "cuda":
        torch.cuda.synchronize()
        device_allocated = torch.cuda.memory_allocated()
        device_reserved = torch.cuda.memory_reserved()
        device_peak = torch.cuda.max_memory_allocated()

    elif device == "mps":
        torch.mps.synchronize()
        device_allocated = torch.mps.current_allocated_memory()
        device_reserved = torch.mps.driver_allocated_memory()
  
    def mib(value):
        return value / 1024**2
  
    print(
        f"[{label}]: "
        f"RSS={mib(rss):.1f} MiB, "
        f"device allocated={mib(device_allocated):.1f} MiB, "
        f"device reserved={mib(device_reserved):.1f} MiB, "
        f"device peak={mib(device_peak):.1f} MiB"
    )
